### ISSUE TITLE
Problem with install

### ISSUE THREAD

**Issue by ghost** [kjetilmjos/node-nmap-viewer#16] opened 2017-07-24 12:34 UTC
I know that its not a issue but i need to contact with you. Can you help me with install this, i did the same you wrote but still in web browser on localhost i cant see anything. Can you help me? I need "tutorial" how to install for beginner. I would be appreciated if you could do that

**Comment by kjetilmjos** [comment] 2017-07-24 19:00
Hi thanks for reaching out. It's been a while since I have used this myself. I will set it up again on my computer tomorrow to see if I can get it working. Try running server.js manually to see if there are any error messages. You might need to run the app as root for nodejs to use port 80

**Comment by kjetilmjos** [comment] 2017-07-25 16:42
Hi again mate, I have updated the Readme file with new installation instructions. I have tested them and it works on my system. Let me know how it works out for you.

**Comment by ghost** [comment] 2017-08-01 17:07
Hi again, sorry for a delay. I'm really newbie but I did everything like you (i hope). Propably everything looks okay till moment INSTALL MONGODB. I copy every line from readme.
After sudo systemctl status mongodb the answer is( before I did sudo service mongod start)
● mongodb.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
I skip this information but after this next step is nodejs datapusher. Again answer 
nodejs datapusher.js
(node:8954) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client

events.js:160
      throw er; // Unhandled 'error' event
      ^
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/home/szymon/node-nmap-viewer-master/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:328:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/home/szymon/node-nmap-viewer-master/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Connection.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/home/szymon/node-nmap-viewer-master/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:177:49)
    at Socket.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

I will try again and again look what I did wrong but, hmm, still don't know where I did a mistake. Really enjoy that answer to me. You are really good guy.

**Comment by kjetilmjos** [comment] 2017-08-01 18:46
The problem is that MongoDB is not installed correctly. The lines should be copied and executed one by one for the commands to work properly. The commands are:

1: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
2: echo "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
3: sudo apt-get update
4: sudo apt-get install -y mongodb-org

You are running ubuntu 16.04 or later at a 64 bit machine?

**Comment by ghost** [comment] 2017-08-01 19:38
Hi! 
I tried this 100times, but I found the solution. I need to add systemctl enable mongod.service, after this looks fine. Sorry for the problem and  thank you  for interest. Now I will test this amazing program.

**Comment by kjetilmjos** [comment] 2017-08-01 20:03
Good to hear you found the solution! the enable parameter is to make the service autostart on computer boot. Should not really be nessecary to get the service to start but anyway.. 
This was just a small program I made for myself to learn more about the technology. If it can be to an inspiration or help I'm glad, but I would recommend to use it only for internal purposes. Keep on posting issues if you have some improvement sugestions or find bugs that needs resolving.

**Closed as completed** 2017-08-02 13:03 UTC
